---
name: Bug Report
description: The following form provides context for your submitted issue.
title: '[Bug]: '
labels:
  - review
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the below report.
  - type: input
    id: version
    attributes:
      label: Version, or commit number if you are using a branch and stipulate your fork if one exists
      description: "If you are running on a branch using git execute this command in order to fetch the latest commit ID: `git log -1`. Please also stipulate if you are using a forked version and include a link to the fork source code."
      placeholder: "0.1"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is. Please include screenshots where relevant.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How To Reproduce
      description: How can we reproduce this issue? (as minimally and as precisely as possible)
      placeholder: A clear and concise description of how to reproduce the issue.
    validations:
      required: true      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct as defined in `/CODE_OF_CONDUCT.md`.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true