name: Feature Request
description: The following form provides context for your requested feature.
title: '[Enhancement]: '
labels:
  - review
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the below report.
  - type: input
    id: version
    attributes:
      label: Version, or commit number if you are using a branch and stipulate your fork if one exists
      description: "If you are running on a branch using git execute this command in order to fetch the latest commit ID: `git log -1`. Please also stipulate if you are using a forked version and include a link to the fork source code."
      placeholder: "0.1"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true      
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct as defined in `/CODE_OF_CONDUCT.md`.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true